name: aes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  crypto: ^3.0.6
  encrypt: ^5.0.3
  mobile_scanner: ^6.0.1
  path_provider: ^2.1.4
  permission_handler: ^10.0.0
  just_audio: ^0.9.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
